---
all:
  hosts:
    awx:
    homepc2:
    enc1a:
    katello:
    kvm:
    laptop:
    ceph-mon:
    osd1:
    osd2:
    osd3:
    www:
  children:
    mons:
      hosts:
        ceph-mon:
    osds:
      hosts:
        osd1:
        osd2:
        osd3:
    rgws:
      hosts:
        www:
    clients:
      hosts:
        homepc2:
        laptop:
    enc1:
      hosts:
        enc1a:
        enc1b:
        enc1c:
        enc1d:
