---
all:
  hosts:
    #gitlab:
    #kat:
    #mas:
    #nuc1:
    #nuc2:
    #nuc3:
    #nuc4:
    #rundeck:
    desktop:
    enc1a:
    kvm:
    laptop:
    mon1:
    mon2:
    mon3:
    osd1:
    osd2:
    osd3:
    www:
  children:
    mons:
      hosts:
        mon1:
        mon2:
        mon3:
    osds:
      hosts:
        osd1:
        osd2:
        osd3:
    rgws:
      hosts:
        www:
    clients:
      hosts:
        desktop:
        laptop:
    enc1:
      hosts:
        enc1a:

