---
- name: Install katello-agent and cutover to Katello repos
  hosts: all
#  tasks:
#  - group_by: key=os_{{ ansible_distribution }}
#
#- hosts: os_CentOS
  gather_facts: no
  become: yes
  roles:
  - katello-host-setup
