---
- name: Query prior rpm if any
  shell: rpm -qa | grep katello-ca-consumer ; exit 0
  args:
    warn: false
  register: rpm
  changed_when: no
  tags: reset

- name: Uninstall prior rpm
  yum:
    name: "{{ rpm.stdout }}"
    state: absent
  when: rpm is defined
  tags: reset

- name: Reenable default repos
  command: "yum-config-manager --enable {{ item }}" 
  with_items:
  - base
  - extras
  - updates
  tags:
  - reset

- name: Install yum-utils
  yum:
    name: yum-utils
    state: present
  tags:
  - deploy
  - reset

- name: Install subscription-manager
  yum:
    name: subscription-manager
    state: present
  tags:
  - deploy

- name: Install katello consumer rpm
  yum:
    name: '{{ katello_remote_rpm }}'
    state: present
    validate_certs: no
  tags: deploy

- name: Disable existing redhat repos
  command: subscription-manager remove --all
  ignore_errors: yes
  tags:
  - reset

- name: Unregister existing subscriptions
  command: subscription-manager unregister
  ignore_errors: yes
  tags:
  - reset

- name: Clean subscription manager
  command: subscription-manager clean
  tags:
  - reset

- name: Clean yum cache
  command: yum clean all 
  args:
    warn: false
  tags:
  - reset

- name: Subscribe with activation key
  redhat_subscription:
    activationkey: '{{ activation_key }}'
    org_id: '{{ org_id }}'
    state: present
  tags:
  - deploy

- name: Disable repos replaced by katello
  command: "yum-config-manager --disable {{ item }}" 
  with_items:
  - base
  - extras
  - updates
  tags:
  - deploy

- name: Install katello-host-tools
  yum:
    name: katello-host-tools
    state: present
  tags:
  - deploy

- name: Uninstall subscription-manager
  yum:
    name: subscription-manager
    state: absent
  tags: reset

