---
- name: install epel-release
  yum: name=epel-release state=latest

- name: install packages
  yum: name={{item}} state=latest
  with_items:
  - htop
  - lshw
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - wget
  - yum-utils 

