---
- name: install epel-release
  yum: name=epel-release state=latest

- name: install packages
  yum:
    name:
    - htop
    - lshw
    - setroubleshoot-server
    - tree
    - vim-enhanced
    - wget
    - yum-utils 
    state: latest

