---
# tasks file for ubuntu_reboot_required
- name: Test whether reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Show whether reboot required
  debug:
    msg: Reboot is required
  when: reboot_required_file.stat.exists

