---
# tasks file for centos_needs_restarting

- name: Test whether reboot required
  shell: needs-restarting -r ; exit 0
  register: result
  changed_when: False

- name: Show whether reboot required
  debug:
    var: result.stdout_lines

