---
# tasks file for ipa-client-install
- name: Install ipa-client
  yum:
    name: ipa-client
    state: present

- name: Configure IPA client and add DNS record to IPA server
  command: "ipa-client-install --unattended --principal=admin@ARK8.US --password={{ freeipa_admin_password }} --mkhomedir --enable-dns-updates"

